// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
///
// await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
// );
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb9O2ymuBSf5qHyDzihF26l6PuYJUCEZs',
    appId: '1:381491556997:web:17517fa0c7139a22f26fec',
    messagingSenderId: '381491556997',
    projectId: 'saknuk-35ef9',
    authDomain: 'saknuk-35ef9.firebaseapp.com',
    storageBucket: 'saknuk-35ef9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1lbvBEvSuN4JAUjlgOcBWDEbl-Ksbc10',
    appId: '1:381491556997:android:2ddcfde293b61ed3f26fec',
    messagingSenderId: '381491556997',
    projectId: 'saknuk-35ef9',
    storageBucket: 'saknuk-35ef9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3FFpk8_aLLv8ARgGpyzgTRUNupO0bOEo',
    appId: '1:381491556997:ios:693a7c2b811327a0f26fec',
    messagingSenderId: '381491556997',
    projectId: 'saknuk-35ef9',
    storageBucket: 'saknuk-35ef9.appspot.com',
    iosBundleId: 'com.example.studenthousingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3FFpk8_aLLv8ARgGpyzgTRUNupO0bOEo',
    appId: '1:381491556997:ios:a2fabed442941daef26fec',
    messagingSenderId: '381491556997',
    projectId: 'saknuk-35ef9',
    storageBucket: 'saknuk-35ef9.appspot.com',
    iosBundleId: 'com.example.studenthousingapp.RunnerTests',
  );
}
